routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function () {
    return view('home');
})->name('home')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('kelas', 'KelasController');
    Route::resource('spp', 'SppController');
    Route::resource('siswa', 'SiswaController');
    Route::resource('petugas', 'PetugasController');
    Route::resource('pembayaran', 'PembayaranController');
    Route::get('/history', 'PembayaranController@history');
    Route::get('/laporan', function () {
        return view('laporan');
    });
    route::get('/laporan/kelas', 'LaporanController@kelas');
    route::get('/laporan/spp', 'LaporanController@spp');
    route::get('/laporan/siswa', 'LaporanController@siswa');
    route::get('/laporan/petugas', 'LaporanController@petugas');
    route::get('/laporan/pembayaran', 'LaporanController@pembayaran');
});

app/Spp.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Spp extends Model
{
    protected $fillable = [
        "tahun",
        "nominal"
    ];
}

app/Http/Controllers/SppController.php
<?php

namespace App\Http\Controllers;

use App\Spp;
use Illuminate\Http\Request;

class SppController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //ambil data max 10
        $data = Spp::paginate(10);
        //membuat variabel tampil yang diisi dengan data
        $tampil['data'] = $data;
        //tampilkan resources/views/spp/index.blade.php beserta variabel tampil
        return view("spp.index", $tampil);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //tampilkan resources/views/spp/create.blade.php
        return view("spp.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validasi inputan
        $this->validate($request, [
            'tahun' => 'required|numeric|digits:4',
            'nominal' => 'required|numeric'
        ]);
        $data = Spp::create($request->all());
        return redirect()->route("spp.index")->with(
            "success",
            "Data berhasil disimpan."
        );
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($spp)
    {
        $data = Spp::findOrFail($spp);
        //tampilkan resources/views/spp/edit.blade.php
        return view("spp.edit", $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $spp)
    {
        //validasi inputan
        $this->validate($request, [
            'tahun' => 'required|numeric|digits:4',
            'nominal' => 'required|numeric'
        ]);

        $data = Spp::findOrFail($spp);
        $data->tahun = $request->tahun;
        $data->nominal = $request->nominal;
        $data->save();

        return redirect()->route("spp.index")->with(
            "success",
            "Data berhasil diubah."
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($spp)
    {
        $data = Spp::findOrFail($spp);
        $data->delete();
    }
}

resources/views/spp/create.blade.php
@extends('adminlte::page')
@section('title', 'SPP')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen SPP</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-warning"></i> Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Tambah SPP
                </div>
                <div class="card-body">
                    <form class="form-horizontal" action="{{ route('spp.store') }}" method="post">
                        @include('spp.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Pace', true)

resources/views/spp/edit.blade.php
@extends('adminlte::page')
@section('title', 'SPP')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen SPP</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-warning"></i> Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Ubah SPP
                </div>
                <div class="card-body">
                    <form class="form-horizontal" action="{{ route('spp.update', ['spp' => $id]) }}" method="post">
                        @method('PUT')
                        @include('spp.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Pace', true)

resources/views/spp/form.blade.php
{{ csrf_field() }}
<div class="form-group">
    <label for="tahun" class="col-sm-2 control-label">Tahun</label>
    <div class="col-sm-2">
        <input type="number" size="4" name="tahun" class="form-control" value="{{ $tahun ?? '' }}">
    </div>
</div>
<div class="form-group">
    <label for="nominal" class="col-sm-2 control-label">Nominal</label>
    <div class="col-sm-5">
        <input type="number" name="nominal" class="form-control" value="{{ $nominal ?? '' }}">
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" class="btn btn-success btn-md" name="simpan" value="Simpan">
        <a href="{{ route('spp.index') }}" class="btn btn-primary" role="button">Batal</a>
    </div>
</div>

resources/views/spp/index.blade.php
@extends('adminlte::page')
@section('title', 'SPP')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen SPP</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-primary btn-md" href="{{ route('spp.create') }}">
                        <i class="fa fa-plus"></i> Tambah
                    </a>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th style="width: 20px">#</th>
                            <th>Tahun</th>
                            <th>Nominal</th>
                            <th style="width: 80px">Aksi</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $no = 1;?>
                        @forelse($data as $item)
                            <tr>
                                <td>
                                    {{ $no }}
                                </td>
                                <td>
                                    {{ $item->tahun }}
                                </td>
                                <td>
                                    {{ $item->nominal }}
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-success" href="{{ route('spp.edit', ['spp' => $item->id]) }}">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <a class="btn btn-primary" onclick="hapus('{{ $item->id }}')" href="#">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            <?php $no++;?>
                        @empty
                            <tr>
                                <td colspan="4">
                                    Tidak ada data.
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix text-right">
                    {{ $data->links() }}
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Sweetalert2', true)
@section('plugins.Pace', true)
@section('js')
    @if (session('success'))
        <script type="text/javascript">
            Swal.fire(
                'Sukses!',
                '{{ session('success') }}',
                'success'
            )
        </script>
    @endif
    <script type="text/javascript">
        function hapus(id) {
            Swal.fire({
                title: 'Konfirmasi',
                text: "Yakin menghapus data ini?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#dd3333',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batal',
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: "/spp/" + id,
                        type: 'DELETE',
                        data: {
                            '_token': $('meta[name=csrf-token]').attr("content"),
                        },
                        success: function (result) {
                            Swal.fire(
                                'Sukses!',
                                'Berhasil Hapus',
                                'success'
                            );
                            location.reload();
                        }
                    });
                }
            })
        }
    </script>
@stop

resources/views/spp/pdf.blade.php
<html>
<head>
    <title>Laporan SPP</title>
</head>
<style>
    @page {
        margin: 10px;
    }

    body {
        margin: 10px;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    table tr th {
        border: 1px solid black;
        background: #c5c5c5;
        padding: 5px;
    }

    table tr td {
        border: 1px solid black;
        padding: 5px;
    }
</style>
<body>
<h1 align="center">Laporan SPP</h1>
<br>
<table>
    <thead>
    <tr>
        <th width="20">No</th>
        <th>Tahun</th>
        <th>Nominal</th>
    </tr>
    </thead>
    <tbody>
    <?php $no = 1;?>
    @foreach($data as $item)
        <tr>
            <td align="center">
                {{ $no }}
            </td>
            <td>
                {{ $item->tahun }}
            </td>
            <td>
                {{ $item->nominal }}
            </td>
        </tr>
        <?php $no++;?>
    @endforeach
    </tbody>
</table>
</body>
</html>