routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function () {
    return view('home');
})->name('home')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('kelas', 'KelasController');
    Route::resource('spp', 'SppController');
    Route::resource('siswa', 'SiswaController');
    Route::resource('petugas', 'PetugasController');
    Route::resource('pembayaran', 'PembayaranController');
    Route::get('/history', 'PembayaranController@history');
    Route::get('/laporan', function () {
        return view('laporan');
    });
    route::get('/laporan/kelas', 'LaporanController@kelas');
    route::get('/laporan/spp', 'LaporanController@spp');
    route::get('/laporan/siswa', 'LaporanController@siswa');
    route::get('/laporan/petugas', 'LaporanController@petugas');
    route::get('/laporan/pembayaran', 'LaporanController@pembayaran');
});

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
//    protected $guarded = [];
    protected $fillable = [
        "nisn",
        "nis",
        "nama",
        "alamat",
        "no_telp",
        "id_kelas",
        "id_spp",
        "id_user"
    ];
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Kelas;
use App\Siswa;
use App\Spp;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        //ambil data max 10
        $data = Siswa::paginate(10);
        //membuat variabel tampil yang diisi dengan data
        foreach ($data as $item) {
            $item->kelas = Kelas::find($item->id_kelas);
            $item->spp = Spp::find($item->id_spp);
//            $item->user = Siswa::find($item->id_user);
            $item->user = Siswa::where('id_user', $item->id_user);
        }
        $tampil['data'] = $data;
        //tampilkan resources/views/siswa/index
        return view("siswa.index", $tampil);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //tampilkan resources/views/siswa/create.blade.php
        $data['kelas'] = Kelas::get();
        $data['spp'] = Spp::get();
        return view("siswa.create", $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validasi inputan
        $this->validate($request, [
            'nisn' => 'required|unique:siswas',
            'nis' => 'required|unique:siswas',
            'nama' => 'required',
            'alamat' => 'required',
            'no_telp' => 'required',
            'id_kelas' => 'required',
            'id_spp' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required',
        ]);

        //enkripsi password
        $enkripsi = Hash::make($request->password);
        $request->merge(['password' => $enkripsi]);
        //isi name dengan nama
        $request->merge(['name' => $request->nama]);
        //isi hak_akses dengan 'siswa'
        $request->merge(['hak_akses' => "siswa"]);
        //buat data User
        $dataUser = User::create($request->all());
        //isi id_siswa
        $request->merge(['id_user' => $dataUser->id]);

        //buat data siswa
        $dataSiswa = Siswa::create($request->all());
        return redirect()->route("siswa.index")->with(
            "success",
            "Data berhasil disimpan."
        );
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($siswa)
    {
        $data = Siswa::findOrFail($siswa);
        $data->kelas = Kelas::get();
        $data->spp = Spp::get();
        $data->user = User::find($data->id_user);
        //tampilkan resources/views/siswa/edit.blade.php
        return view("siswa.edit", $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $siswa)
    {
        //validasi inputan
        $this->validate($request, [
            'nis' => 'required',
            'nama' => 'required',
            'alamat' => 'required',
            'no_telp' => 'required',
            'id_kelas' => 'required',
            'id_spp' => 'required',
            'email' => 'required|email',
        ]);
        $dataSiswa = Siswa::findOrFail($siswa);
        $dataSiswa->nis = $request->nis;
        $dataSiswa->nama = $request->nama;
        $dataSiswa->alamat = $request->alamat;
        $dataSiswa->no_telp = $request->no_telp;
        $dataSiswa->id_kelas = $request->id_kelas;
        $dataSiswa->id_spp = $request->id_spp;
        $dataSiswa->save();
        $dataUser = User::findOrFail($dataSiswa->id_user);
        $dataUser->name = $request->nama;
        $dataUser->email = $request->email;
        //jika password tidak kosong
        if ($request->password != "") {
            $enkripsi = Hash::make($request->password);
            $dataUser->password = $enkripsi;
        }
        $dataUser->save();

        return redirect()->route("siswa.index")->with(
            "success",
            "Data berhasil diubah."
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($siswa)
    {
        $dataSiswa = Siswa::findOrFail($siswa);
        $dataSiswa->delete();
        $dataUser = User::findOrFail($dataSiswa->id_user);
        $dataUser->delete();
    }
}

resources/views/siswa/create.blade.php
@extends('adminlte::page')
@section('title', 'Siswa')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen Siswa</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-warning"></i> Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Tambah Siswa
                </div>
                <div class="card-body">
                    <form class="form-horizontal" action="{{ route('siswa.store') }}" method="post">
                        @include('siswa.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Pace', true)

resources/views/siswa/edit.blade.php
@extends('adminlte::page')
@section('title', 'Siswa')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen Siswa</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-warning"></i> Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Ubah Siswa
                </div>
                <div class="card-body">
                    <form class="form-horizontal" action="{{ route('siswa.update', ['siswa' => $nisn]) }}"
                          method="post">
                        @method('PUT')
                        @include('siswa.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Pace', true)
@section('js')
    <script type="text/javascript">
        $("#nisn").prop('disabled', true);
    </script>
@stop

resources/views/siswa/form.blade.php
{{ csrf_field() }}
<div class="form-group">
    <label for="nisn" class="col-sm-2 control-label">NISN</label>
    <div class="col-sm-10">
        <input type="text" name="nisn" id="nisn" class="form-control" value="{{ $nisn ?? '' }}">
    </div>
</div>
<div class="form-group">
    <label for="nis" class="col-sm-2 control-label">NIS</label>
    <div class="col-sm-10">
        <input type="text" name="nis" class="form-control" value="{{ $nis ?? '' }}">
    </div>
</div>
<div class="form-group">
    <label for="nama" class="col-sm-2 control-label">Nama</label>
    <div class="col-sm-10">
        <input type="text" name="nama" class="form-control" value="{{ $nama ?? '' }}">
    </div>
</div>
<div class="form-group">
    <label for="alamat" class="col-sm-2 control-label">Alamat</label>
    <div class="col-sm-10">
        <input type="text" name="alamat" class="form-control" value="{{ $alamat ?? '' }}">
    </div>
</div>
<div class="form-group">
    <label for="no_telp" class="col-sm-2 control-label">No Telp</label>
    <div class="col-sm-10">
        <input type="text" name="no_telp" class="form-control" value="{{ $no_telp ?? '' }}">
    </div>
</div>
<label for="email" class="col-sm-2 control-label">Email</label>
<div class="col-sm-10">
    <input type="email" name="email" class="form-control" value="{{ $user->email ?? '' }}">
</div>
</div>
<div class="form-group">
    <label for="password" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <input type="password" name="password" class="form-control" value="{{ $password ?? '' }}">
    </div>
</div>
<div class="form-group">
    <label for="id_kelas" class="col-sm-2 control-label">Kelas</label>
    <div class="col-sm-10">
        <select name="id_kelas" class="form-control">
            @foreach($kelas as $item)
                <option value="{{ $item->id }}" {{ ( ($id_kelas??'')==$item->id) ? 'selected' : '' }}>
                    {{ $item->nama_kelas }} - {{ $item->kompetensi_keahlian }}
                </option>
            @endforeach
        </select>
    </div>
</div>
<div class="form-group">
    <label for="id_spp" class="col-sm-2 control-label">SPP</label>
    <div class="col-sm-10">
        <select name="id_spp" class="form-control">
            @foreach($spp as $item)
                <option value="{{ $item->id }}" {{ ( ($id_spp??'')==$item->id) ? 'selected' : '' }}>
                    {{ $item->tahun }} - {{ $item->nominal }}
                </option>
            @endforeach
        </select>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" class="btn btn-success btn-md" name="simpan" value="Simpan">
        <a href="{{ route('siswa.index') }}" class="btn btn-primary" role="button">Batal</a>
    </div>
</div>

resources/views/siswa/index.blade.php
@extends('adminlte::page')
@section('title', 'Siswa')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen Siswa</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-primary btn-md" href="{{ route('siswa.create') }}">
                        <i class="fa fa-plus"></i> Tambah
                    </a>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th style="width: 20px">#</th>
                            <th>NIS</th>
                            <th>Nama</th>
                            <th>Kelas</th>
                            <th>SPP</th>
                            <th style="width: 80px">Aksi</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $no = 1;?>
                        @forelse($data as $item)
                            <tr>
                                <td>
                                    {{ $no }}
                                </td>
                                <td>
                                    {{ $item->nis }}
                                </td>
                                <td>
                                    {{ $item->nama }}
                                </td>
                                <td>
                                    {{ $item->kelas->nama_kelas }} - {{ $item->kelas->kompetensi_keahlian }}
                                </td>
                                <td>
                                    {{ $item->spp->tahun }} - {{ $item->spp->nominal }}
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-success"
                                           href="{{ route('siswa.edit', ['siswa'=>$item->nisn]) }}">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <a class="btn btn-primary" onclick="hapus('{{ $item->nisn }}')" href="#">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            <?php $no++;?>
                        @empty
                            <tr>
                                <td colspan="6">
                                    Tidak ada data.
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix text-right">
                    {{ $data->links() }}
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Sweetalert2', true)
@section('plugins.Pace', true)
@section('js')
    @if (session('success'))
        <script type="text/javascript">
            Swal.fire(
                'Sukses!',
                '{{ session('success') }}',
                'success'
            )
        </script>
    @endif
    <script type="text/javascript">
        function hapus(id) {
            Swal.fire({
                title: 'Konfirmasi',
                text: "Yakin menghapus data ini?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#dd3333',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batal',
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: "/siswa/" + id,
                        type: 'DELETE',
                        data: {
                            '_token': $('meta[name=csrf-token]').attr("content"),
                        },
                        success: function (result) {
                            Swal.fire(
                                'Sukses!',
                                'Berhasil Hapus',
                                'success'
                            );
                            location.reload();
                        }
                    });
                }
            })
        }
    </script>
@stop

resources/views/siswa/pdf.blade.php
<html>
<head>
    <title>Laporan Siswa</title>
</head>
<style>
    @page {
        margin: 10px;
    }

    body {
        margin: 10px;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    table tr th {
        border: 1px solid black;
        background: #c5c5c5;
        padding: 5px;
    }

    table tr td {
        border: 1px solid black;
        padding: 5px;
    }
</style>
<body>
<h1 align="center">Laporan Siswa</h1>
<br>
<table>
    <thead>
    <tr>
        <th width="20">No</th>
        <th>NIS</th>
        <th>Nama</th>
        <th>Kelas</th>
        <th>SPP</th>
    </tr>
    </thead>
    <tbody>
    <?php $no = 1;?>
    @foreach($data as $item)
        <tr>
            <td align="center">
                {{ $no }}
            </td>
            <td>
                {{ $item->nis }}
            </td>
            <td>
                {{ $item->nama }}
            </td>
            <td>
                {{ $item->kelas->nama_kelas }} <br> {{ $item->kelas->kompetensi_keahlian }}
            </td>
            <td>
                {{ $item->spp->tahun }} - {{ $item->spp->nominal }}
            </td>
        </tr>
        <?php $no++;?>
    @endforeach
    </tbody>
</table>
</body>
</html>