routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function () {
    return view('home');
})->name('home')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('kelas', 'KelasController');
    Route::resource('spp', 'SppController');
    Route::resource('siswa', 'SiswaController');
    Route::resource('petugas', 'PetugasController');
    Route::resource('pembayaran', 'PembayaranController');
    Route::get('/history', 'PembayaranController@history');
    Route::get('/laporan', function () {
        return view('laporan');
    });
    route::get('/laporan/kelas', 'LaporanController@kelas');
    route::get('/laporan/spp', 'LaporanController@spp');
    route::get('/laporan/siswa', 'LaporanController@siswa');
    route::get('/laporan/petugas', 'LaporanController@petugas');
    route::get('/laporan/pembayaran', 'LaporanController@pembayaran');
});

app/Pembayaran.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pembayaran extends Model
{
    protected $fillable = [
        "tgl_bayar",
        "jumlah_bayar"
    ];
}

app/Http/Controllers/PembayaranController.php
<?php

namespace App\Http\Controllers;

use App\Pembayaran;
use App\Siswa;
use App\Spp;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PembayaranController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //ambil data max 10
        $data = Pembayaran::paginate(10);
        //membuat variabel tampil yang diisi dengan data
        foreach ($data as $item) {
            $item->siswa = Siswa::find($item->nisn);
            $item->spp = Spp::find($item->id_spp);
            $item->user = User::find($item->id_user);
        }
        $tampil['data'] = $data;
        //tampilkan resources/views/pembayaran/index.blade.php
        return view("pembayaran.index", $tampil);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //tampilkan resources/views/siswa/create.blade.php
        $siswa = Siswa::get();
        foreach ($siswa as $item) {
            $spp = Spp::find($item->id_spp);
            $item->options = $item->nisn . " " . $item->nama . " | SPP " . $spp->tahun . " - " . $spp->nominal;
        }
        $data['siswa'] = $siswa;
        return view("pembayaran.create", $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //ambil data spp
        $id_spp = Siswa::find($request->nisn)->id_spp;
        $spp = Spp::find($id_spp);
        //validasi inputan
        $this->validate($request, [
            'tgl_bayar' => 'required|date',
            'nisn' => 'required',
            'jumlah_bayar' => 'required|lt:' . $spp->nominal,
        ]);
        //isi id_user dengan id user yang login
        $id_user = Auth::user()->id;
        $request->merge(['id_user' => $id_user]);
        //isi id_spp dengan id_spp milik siswa
        $id_spp = Siswa::find($request->nisn)->id_spp;
        $request->merge(['id_spp' => $id_spp]);
        $data = Pembayaran::create($request->all());
        return redirect()->route("pembayaran.index")->with(
            "success",
            "Data berhasil disimpan."
        );
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($pembayaran)
    {
        $data = Pembayaran::findOrFail($pembayaran);
        $siswa = Siswa::get();
        foreach ($siswa as $item) {
            $spp = Spp::find($item->id_spp);
            $item->options = $item->nisn . " " . $item->nama . " | SPP " . $spp->tahun . " - " . $spp->nominal;
        }
        $data->siswa = $siswa;

        //tampilkan resources/views/pembayaran/edit.blade.php
        return view("pembayaran.edit", $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $pembayaran)
    {
        //ambil data spp
        $id_spp = Siswa::find($request->nisn)->id_spp;
        $spp = Spp::find($id_spp);
        //validasi inputan
        $this->validate($request, [
            'tgl_bayar' => 'required|date',
            'nisn' => 'required',
            'jumlah_bayar' => 'required|lt:' . $spp->nominal,
        ]);
        $data = Pembayaran::findOrFail($pembayaran);
        $data->nisn = $request->nisn;
        $data->tgl_bayar = $request->tgl_bayar;
        //isi id_spp dengan id_spp milik siswa
        $id_spp = Siswa::find($request->nisn)->id_spp;
        $data->id_spp = $id_spp;
        $data->jumlah_bayar = $request->jumlah_bayar;
        $data->save();

        return redirect()->route("pembayaran.index")->with(
            "success",
            "Data berhasil diubah."
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($pembayaran)
    {
        $data = Pembayaran::findOrFail($pembayaran);
        $data->delete();
    }

    public function history()
    {
        //cek user
        $user = Auth::user();
        if ($user->hak_akses == "siswa") {
            //ambil data berdasarkan nisn maksimal 10 data
            $siswa = Siswa::where("id_user", $user->id)->first();
            $nisn = $siswa->nisn;
            $data = Pembayaran::where("nisn", $nisn)->paginate(10);
        } else {
            //ambil data maksimal 10 data
            $data = Pembayaran::paginate(10);
        }

        //membuat variabel tampil yang diisi dengan data
        foreach ($data as $item) {
            $item->siswa = Siswa::find($item->nisn);
            $item->spp = Spp::find($item->id_spp);
            $item->user = User::find($item->id_user);
        }
        $tampil['data'] = $data;
        //tampilkan resources/views/pembayaran/history.blade.php beserta variabel tampil
        return view("pembayaran.history", $tampil);
    }
}

resources/views/pembayaran/create.blade.php
@extends('adminlte::page')
@section('title', 'Pembayaran')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen Pembayaran</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-warning"></i> Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Tambah Pembayaran
                </div>
                <div class="card-body">
                    <form class="form-horizontal" action="{{ route('pembayaran.store') }}" method="post">
                        @include('pembayaran.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Pace', true)
@section('plugins.DateRangePicker', true)
@section('js')
    <script type="text/javascript">
        $("#tgl_bayar").daterangepicker({
            autoclose: true,
            todayBtn: true,
            timePicker: true,
            singleDatePicker: true,
            locale: {
                format: 'Y/MM/DD HH:mm:ss'
            }
        });
    </script>
@stop

resources/views/pembayaran/edit.blade.php
@extends('adminlte::page')
@section('title', 'Pembayaran')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen Pembayaran</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-warning"></i> Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Ubah Pembayaran
                </div>
                <div class="card-body">
                    <form class="form-horizontal" action="{{ route('pembayaran.update', ['pembayaran'= $id]) }}"
                          method="post">
                        @method('PUT')
                        @include('pembayaran.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Pace', true)
@section('plugins.DateRangePicker', true)
@section('js')
    <script type="text/javascript">
        $("#tgl_bayar").daterangepicker({
            autoclose: true,
            todayBtn: true,
            timePicker: true,
            singleDatePicker: true,
            locale: {
                format: 'Y/MM/DD HH:mm:ss'
            }
        });
    </script>
@stop

resources/views/pembayaran/form.blade.php
{{ csrf_field() }}
<div class="form-group">
    <label for="tgl_bayar" class="col-sm-2 control-label">Tanggal Bayar</label>
    <div class="col-sm-3">
        <input type="text" name="tgl_bayar" id="tgl_bayar" class="form-control" value="{{ $tgl_bayar ?? '' }}">
    </div>
</div>
<div class="form-group">
    <label for="id_kelas" class="col-sm-2 control-label">Siswa</label>
    <div class="col-sm-10">
        <select name="nisn" class="form-control">
            @foreach($siswa as $item)
                <option value="{{ $item->nisn }}" {{ ( ($nisn??'')==$item->nisn) ? 'selected' : '' }}>
                    {{ $item->options }}
                </option>
            @endforeach
        </select>
    </div>
</div>
<div class="form-group">
    <label for="jumlah_bayar" class="col-sm-2 control-label">Jumlah Bayar</label>
    <div class="col-sm-5">
        <input type="number" name="jumlah_bayar" class="form-control" value="{{ $jumlah_bayar ?? '' }}">
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" class="btn btn-success btn-md" name="simpan" value="Simpan">
        <a href="{{ route('pembayaran.index') }}" class="btn btn-primary" role="button">Batal</a>
    </div>
</div>

resources/views/pembayaran/history.blade.php
@extends('adminlte::page')
@section('title', 'History Pembayaran')
@section('content_header')
    <h1 class="m-0 text-dark">History Pembayaran</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th style="width: 20px">#</th>
                            <th>Tgl Bayar</th>
                            <th>Siswa</th>
                            <th>SPP</th>
                            <th>Jumlah</th>
                            <th>Petugas</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $no = 1;?>
                        @forelse($data as $item)
                            <tr>
                                <td>
                                    {{ $no }}
                                </td>
                                <td>
                                    {{ $item->tgl_bayar }}
                                </td>
                                <td>
                                    {{ $item->nisn }} - {{ $item->siswa->nama }}
                                </td>
                                <td>
                                    {{ $item->spp->tahun }} - {{ $item->spp->nominal }}
                                </td>
                                <td>
                                    {{ $item->jumlah_bayar }}
                                </td>
                                <td>
                                    {{ $item->user->name }}
                                </td>
                            </tr>
                            <?php $no++;?>
                        @empty
                            <tr>
                                <td colspan="6">
                                    Tidak ada data.
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix text-right">
                    {{ $data->links() }}
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Pace', true)

resources/views/pembayaran/index.blade.php
@extends('adminlte::page')
@section('title', 'Pembayaran')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen Pembayaran</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-primary btn-md" href="{{ route('pembayaran.create') }}">
                        <i class="fa fa-plus"></i> Tambah
                    </a>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th style="width: 20px">#</th>
                            <th>Tgl Bayar</th>
                            <th>Siswa</th>
                            <th>SPP</th>
                            <th>Jumlah</th>
                            <th>Petugas</th>
                            <th style="width: 80px">Aksi</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $no = 1;?>
                        @forelse($data as $item)
                            <tr>
                                <td>
                                    {{ $no }}
                                </td>
                                <td>
                                    {{ $item->tgl_bayar }}
                                </td>
                                <td>
                                    {{ $item->nisn }} - {{ $item->siswa->nama }}
                                </td>
                                <td>
                                    {{ $item->spp->tahun }} - {{ $item->spp->nominal }}
                                </td>
                                <td>
                                    {{ $item->jumlah_bayar }}
                                </td>
                                <td>
                                    {{ $item->user->name }}
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-success"
                                           href="{{ route('pembayaran.edit', ['pembayaran'=>$item->id]) }}">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <a class="btn btn-primary" onclick="hapus('{{ $item->id }}')" href="#">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            <?php $no++;?>
                        @empty
                            <tr>
                                <td colspan="7">
                                    Tidak ada data.
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix text-right">
                    {{ $data->links() }}
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Sweetalert2', true)
@section('plugins.Pace', true)
@section('js')
    @if (session('success'))
        <script type="text/javascript">
            Swal.fire(
                'Sukses!',
                '{{ session('success') }}',
                'success'
            )
        </script>
    @endif
    <script type="text/javascript">
        function hapus(id) {
            Swal.fire({
                title: 'Konfirmasi',
                text: "Yakin menghapus data ini?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#dd3333',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batal',
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: "/pembayaran/" + id,
                        type: 'DELETE',
                        data: {
                            '_token': $('meta[name=csrf-token]').attr("content"),
                        },
                        success: function (result) {
                            Swal.fire(
                                'Sukses!',
                                'Berhasil Hapus',
                                'success'
                            );
                            location.reload();
                        }
                    });
                }
            })
        }
    </script>
@stop

resources/views/pembayaran/pdf.blade.php
<head>
    <title>Laporan Pembayaran</title>
</head>
<style>
    @page {
        margin: 10px;
    }

    body {
        margin: 10px;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    table tr th {
        border: 1px solid black;
        background: #c5c5c5;
        padding: 5px;
    }

    table tr td {
        border: 1px solid black;
        padding: 5px;
    }
</style>
<body>
<h1 align="center">Laporan Pembayaran</h1>
<br>
<table>
    <thead>
    <tr>
        <th width="20">No</th>
        <th>Tgl Bayar</th>
        <th>Siswa</th>
        <th>SPP</th>
        <th>Jumlah</th>
        <th>Petugas</th>
    </tr>
    </thead>
    <tbody>
    <?php $no = 1;?>
    @foreach($data as $item)
        <tr>
            <td align="center">
                {{ $no }}
            </td>
            <td>
                {{ $item->tgl_bayar }}
            </td>
            <td>
                {{ $item->nisn }}<br>{{ $item->siswa->nama }}
            </td>
            <td>
                {{ $item->spp->tahun }}<br>{{ $item->spp->nominal }}
            </td>
            <td>
                {{ $item->jumlah_bayar }}
            </td>
            <td>
                {{ $item->user->name }}
            </td>
        </tr>
        <?php $no++;?>
    @endforeach
    </tbody>
</table>
</body>
</html>