routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function () {
    return view('home');
})->name('home')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('kelas', 'KelasController');
    Route::resource('spp', 'SppController');
    Route::resource('siswa', 'SiswaController');
    Route::resource('petugas', 'PetugasController');
    Route::resource('pembayaran', 'PembayaranController');
    Route::get('/history', 'PembayaranController@history');
    Route::get('/laporan', function () {
        return view('laporan');
    });
    route::get('/laporan/kelas', 'LaporanController@kelas');
    route::get('/laporan/spp', 'LaporanController@spp');
    route::get('/laporan/siswa', 'LaporanController@siswa');
    route::get('/laporan/petugas', 'LaporanController@petugas');
    route::get('/laporan/pembayaran', 'LaporanController@pembayaran');
});

app/Kelas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    protected $fillable = [
        "nama_kelas",
        "kompetensi_keahlian"
    ];
}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use App\Kelas;
use Illuminate\Http\Request;

class KelasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //ambil data max 10
        $data = Kelas::paginate(10);
        //membuat variabel tampil yang diisi dengan data
        $tampil['data'] = $data;
        //tampilkan resources/views/kelas/index.blade.php beserta variabel tampil
        return view("kelas.index", $tampil);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //tampilkan resources/views/kelas/create.blade.php
        return view("kelas.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validasi inputan
        $this->validate($request, [
            'nama_kelas' => 'required|unique:kelas',
            'kompetensi_keahlian' => 'required'
        ]);
        $data = Kelas::create($request->all());
        return redirect()->route("kelas.index")->with(
            "success",
            "Data berhasil disimpan."
        );
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($kelas)
    {
        $data = Kelas::findOrFail($kelas);
        //tampilkan resources/views/kelas/edit.blade.php
        return view("kelas.edit", $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $kelas)
    {
        //validasi inputan
        $this->validate($request, [
            'nama_kelas' => 'required',
            'kompetensi_keahlian' => 'required'
        ]);
        $data = Kelas::findOrFail($kelas);
        $data->nama_kelas = $request->nama_kelas;
        $data->kompetensi_keahlian = $request->kompetensi_keahlian;
        $data->save();

        return redirect()->route("kelas.index")->with(
            "success",
            "Data berhasil diubah."
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($kelas)
    {
        $data = Kelas::findOrFail($kelas);
        $data->delete();
    }
}

resources/views/kelas/create.blade.php
@extends('adminlte::page')
@section('title', 'Kelas')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen Kelas</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-warning"></i> Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Tambah Kelas
                </div>
                <div class="card-body">
                    <form class="form-horizontal" action="{{ route('kelas.store') }}" method="post">
                        @include('kelas.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Pace', true)

resources/views/kelas/edit.blade.php
@extends('adminlte::page')
@section('title', 'Kelas')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen Kelas</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-warning"></i> Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Ubah Kelas
                </div>
                <div class="card-body">
                    <form class="form-horizontal" action="{{ route('kelas.update', ['kela' => $id]) }}" method="post">
                        @method('PUT')
                        @include('kelas.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Pace', true)

resources/views/kelas/form.blade.php
{{ csrf_field() }}
<div class="form-group">
    <label for="nama_kelas" class="col-sm-2 control-label">Nama Kelas</label>
    <div class="col-sm-10">
        <input type="text" name="nama_kelas" class="form-control" value="{{ $nama_kelas ?? '' }}">
    </div>
</div>
<div class="form-group">
    <label for="kompetensi_keahlian" class="col-sm-2 control-label">Kompetensi Keahlian</label>
    <div class="col-sm-10">
        <input type="text" name="kompetensi_keahlian" class="form-control" value="{{ $kompetensi_keahlian ?? '' }}">
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" class="btn btn-success btn-md" name="simpan" value="Simpan">
        <a href="{{ route('kelas.index') }}" class="btn btn-primary" role="button">Batal</a>
    </div>
</div>

resources/views/kelas/index.blade.php
@extends('adminlte::page')
@section('title', 'Kelas')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen Kelas</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-primary btn-md" href="{{ route('kelas.create') }}">
                        <i class="fa fa-plus"></i> Tambah
                    </a>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th style="width: 20px">#</th>
                            <th>Nama Kelas</th>
                            <th>Kompetensi Keahlian</th>
                            <th style="width: 10%">Aksi</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $no = 1;?>
                        @forelse($data as $item)
                            <tr>
                                <td>
                                    {{ $no }}
                                </td>
                                <td>
                                    {{ $item->nama_kelas }}
                                </td>
                                <td>
                                    {{ $item->kompetensi_keahlian }}
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-success"
                                           href="{{ route('kelas.edit', ['kela' => $item->id]) }}">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <a class="btn btn-primary" onclick="hapus('{{ $item->id }}')" href="#">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            <?php $no++;?>
                        @empty
                            <tr>
                                <td colspan="4">
                                    Tidak ada data.
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div
                <div class="card-footer clearfix text-right">
                    {{ $data->links() }}
                </div>
            </div>
        </div>
    </div>
@stop
@section('plugins.Sweetalert2', true)
@section('plugins.Pace', true)
@section('js')
    @if (session('success'))
        <script type="text/javascript">
            Swal.fire(
                'Sukses!',
                '{{ session('success') }}',
                'success'
            )
        </script>
    @endif
    <script type="text/javascript">
        function hapus(id) {
            Swal.fire({
                title: 'Konfirmasi',
                text: "Yakin menghapus data ini?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#dd3333',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batal',
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: "/kelas/" + id,
                        type: 'DELETE',
                        data: {
                            '_token': $('meta[name=csrf-token]').attr("content"),
                        },
                        success: function (result) {
                            Swal.fire(
                                'Sukses!',
                                'Berhasil Hapus',
                                'success'
                            );
                            location.reload();
                        }
                    });
                }
            })
        }
    </script>
@stop

resources/views/kelas/pdf.blade.php
<html>
<head>
    <title>Laporan Kelas</title>
</head>
<style>
    @page {
        margin: 10px;
    }

    body {
        margin: 10px;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    table tr th {
        border: 1px solid black;
        background: #c5c5c5;
        padding: 5px;
    }

    table tr td {
        border: 1px solid black;
        padding: 5px;
    }
</style>
<body>
<h1 align="center">Laporan Kelas</h1>
<br>
<table>
    <thead>
    <tr>
        <th width="20">No</th>
        <th>Nama Kelas</th>
        <th>Kompetensi Keahlian</th>
    </tr>
    </thead>
    <tbody>
    <?php $no = 1;?>
    @foreach($data as $item)
        <tr>
            <td align="center">
                {{ $no }}
            </td>
            <td>
                {{ $item->nama_kelas }}
            </td>
            <td>
                {{ $item->kompetensi_keahlian }}
            </td>
        </tr>
        <?php $no++;?>
    @endforeach
    </tbody>
</table>
</body>
</html>